name: TrackedJSON CI Tasks

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install Parent Folder
        run: npm install
      - name: Ensure no package-lock.json changes
        run: git diff --exit-code
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
        env:
          CI: true
